services:
  # 1. Physics Engine (OSRM)
  osrm:
    image: osrm/osrm-backend:latest
    container_name: osrm-backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    command: osrm-routed --algorithm mld /data/map.osrm

  # 2. Prediction Service (Brain)
  eta-engine:
    build: .
    container_name: eta-engine
    restart: always
    ports:
      - "8000:8000"
    environment:
      - OSRM_HOST=http://osrm:5000
      - REDIS_HOST=redis
      - KAFKA_BROKER=kafka:29092
    volumes:
      #  Mount current directory (.) to /app inside container
      #  any file created in /app appears on your Windows machine instantly.
      - .:/app
    depends_on:
      - osrm
      - redis
      - kafka

  # 3. Feature Store (Memory)
  redis:
    image: redis:alpine
    container_name: feature-store
    restart: always
    ports:
      - "6379:6379"

  # 4. Event Bus (Kafka)
  kafka:
    image: apache/kafka:latest
    container_name: kafka-broker
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: CONTROLLER://:9093,INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

volumes:
  kafka_data: